name: GitHub Repo README
description: Updates README with a user's repositories
author: 6ixfalls

inputs:
  GH_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing to the repo"
    default: "Updated latest README repositories"
    required: false
  MAX_LINES:
    description: "The maximum number of lines populated in your readme file"
    default: 20
    required: false

branding:
  color: yellow
  icon: activity

runs:
  using: node16
  main: dist/index.js