name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 6ixfalls/6ixfalls@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
