name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-code@v3
        with:
          node-version: 16.13.0
      - run: node dist/index.js
        with:
          - GH_USERNAME: ${{ github.repository_owner }}
          - COMMIT_MSG: "Updated latest repository activity"
          - MAX_LINES: 20
          - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}